/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wechat_webapi_util_BZPCXCode */

#ifndef _Included_com_wechat_webapi_util_BZPCXCode
#define _Included_com_wechat_webapi_util_BZPCXCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wechat_webapi_util_BZPCXCode
 * Method:    BZPGetLogisticalID
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wechat_webapi_util_BZPCXCode_BZPGetLogisticalID
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wechat_webapi_util_BZPCXCode
 * Method:    BZPDataVerify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wechat_webapi_util_BZPCXCode_BZPDataVerify
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_wechat_webapi_util_BZPCXCode
 * Method:    BZPGetSerialCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wechat_webapi_util_BZPCXCode_BZPGetSerialCode
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
