package com.easylotto.core.entity.user;

import java.util.Date;

/**
 * AbstractEcpEcardOper generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractEcpUserFundLog implements java.io.Serializable {

	// Fields

	private Long int_rec_id;
	private Long int_account_id;
	private Integer int_oper_type;
	private Date dt_oper_time;
	private Double dec_amount;
	private String vc_bill_no;
	private Double dec_balance;
	private Integer int_account_type;

	// Constructors

	/** default constructor */
	public AbstractEcpUserFundLog() {
	}

	/** full constructor */
	public AbstractEcpUserFundLog(Long int_rec_id, Long int_account_id,
			Integer int_oper_type, Date dt_oper_time, Double dec_amount,
			String vc_bill_no, Double dec_balance, Integer int_account_type) {
		this.int_rec_id = int_rec_id;
		this.int_account_id = int_account_id;
		this.int_oper_type = int_oper_type;
		this.dt_oper_time = dt_oper_time;
		this.dec_amount = dec_amount;
		this.vc_bill_no = vc_bill_no;
		this.dec_balance = dec_balance;
		this.int_account_type = int_account_type;
	}
	
	// Property accessors

	public Long getInt_rec_id() {
		return int_rec_id;
	}

	public void setInt_rec_id(Long int_rec_id) {
		this.int_rec_id = int_rec_id;
	}

	public Long getInt_account_id() {
		return int_account_id;
	}

	public void setInt_account_id(Long int_account_id) {
		this.int_account_id = int_account_id;
	}

	public Integer getInt_oper_type() {
		return int_oper_type;
	}

	public void setInt_oper_type(Integer int_oper_type) {
		this.int_oper_type = int_oper_type;
	}

	public Date getDt_oper_time() {
		return dt_oper_time;
	}

	public void setDt_oper_time(Date dt_oper_time) {
		this.dt_oper_time = dt_oper_time;
	}

	public Double getDec_amount() {
		return dec_amount;
	}

	public void setDec_amount(Double dec_amount) {
		this.dec_amount = dec_amount;
	}

	public String getVc_bill_no() {
		return vc_bill_no;
	}

	public void setVc_bill_no(String vc_bill_no) {
		this.vc_bill_no = vc_bill_no;
	}

	public Double getDec_balance() {
		return dec_balance;
	}

	public void setDec_balance(Double dec_balance) {
		this.dec_balance = dec_balance;
	}

	public Integer getInt_account_type() {
		return int_account_type;
	}

	public void setInt_account_type(Integer int_account_type) {
		this.int_account_type = int_account_type;
	}

	


}