package com.easylotto.core.entity.user;

import java.util.Date;

/**
 * AbstractEcpEcard generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractEcpUser implements java.io.Serializable {

	// Fields

	private Long int_account_id;
	private String vc_account;// VC_ACCOUNT
	private String vc_password;//
	private Long int_acc_type;// 用户类型 1 会员账户
	private Long int_acc_status;// 用户状态 0 正常 1锁定
	private Long int_gen_type;// 用户来源 1 网站 2客户端 3 WAP
	private Double dec_present_amount;// 赠送账户
	private Double dec_preeze_amount;// 冻结余额
	private Date dt_last_time;// 最后登录时间
	private Long int_user_score;// 积分账户
	private Double dec_paypal_amount;// 可用余额/可提现金额
	private Double dec_nopaypal_amount;// 不可提现金额
	private Date dt_reg_date;// 注册时间
	private String vc_last_ip;// 最后登录IP
	private String vc_pay_password;// 支付密码
	private Double dec_extra_account; //加奖账户
	private Double dec_lottery_bean; //彩豆账户
	private String vc_open_id;
	private String vc_from;
	// Constructors

	/** default constructor */
	public AbstractEcpUser() {
	}

	/** minimal constructor */

	/** full constructor */
	public AbstractEcpUser(Long int_account_id, String vc_account,
			String vc_password, Long int_acc_type, Long int_acc_status,
			Long int_gen_type, Double dec_present_amount,
			Double dec_preeze_amount, Date dt_last_time, Long int_user_score,
			Double dec_paypal_amount, Double dec_nopaypal_amount,
			Date dt_reg_date, String vc_last_ip, String vc_pay_password,
			Double dec_extra_account,Double dec_lottery_bean,String vc_open_id) {
		this.int_account_id = int_account_id;
		this.vc_account = vc_account;
		this.vc_password = vc_password;
		this.int_acc_type = int_acc_type;
		this.int_acc_status = int_acc_status;
		this.int_gen_type = int_gen_type;
		this.dec_present_amount = dec_present_amount;
		this.dec_preeze_amount = dec_preeze_amount;
		this.dt_last_time = dt_last_time;
		this.int_user_score = int_user_score;
		this.dec_paypal_amount = dec_paypal_amount;
		this.dec_nopaypal_amount = dec_nopaypal_amount;
		this.dt_reg_date = dt_reg_date;
		this.vc_last_ip = vc_last_ip;
		this.vc_pay_password = vc_pay_password;
		this.dec_extra_account = dec_extra_account;
		this.dec_lottery_bean = dec_lottery_bean;
		this.vc_open_id = vc_open_id;
	}
		
	// Property accessors

	public AbstractEcpUser(Long int_account_id, String vc_account,
				String vc_password, Long int_acc_type, Long int_acc_status,
				Double dec_paypal_amount, Date dt_reg_date) {
			this.int_account_id = int_account_id;
			this.vc_account = vc_account;
			this.vc_password = vc_password;
			this.int_acc_type = int_acc_type;
			this.int_acc_status = int_acc_status;
			this.dec_paypal_amount = dec_paypal_amount;
			this.dt_reg_date = dt_reg_date;
		}

	public Long getInt_account_id() {
		return int_account_id;
	}

	public void setInt_account_id(Long int_account_id) {
		this.int_account_id = int_account_id;
	}

	public String getVc_account() {
		return vc_account;
	}

	public void setVc_account(String vc_account) {
		this.vc_account = vc_account;
	}

	public String getVc_password() {
		return vc_password;
	}

	public void setVc_password(String vc_password) {
		this.vc_password = vc_password;
	}

	public Long getInt_acc_type() {
		return int_acc_type;
	}

	public void setInt_acc_type(Long int_acc_type) {
		this.int_acc_type = int_acc_type;
	}

	public Long getInt_acc_status() {
		return int_acc_status;
	}

	public void setInt_acc_status(Long int_acc_status) {
		this.int_acc_status = int_acc_status;
	}

	public Long getInt_gen_type() {
		return int_gen_type;
	}

	public void setInt_gen_type(Long int_gen_type) {
		this.int_gen_type = int_gen_type;
	}

	public Double getDec_present_amount() {
		return dec_present_amount;
	}

	public void setDec_present_amount(Double dec_present_amount) {
		this.dec_present_amount = dec_present_amount;
	}

	public Double getDec_preeze_amount() {
		return dec_preeze_amount;
	}

	public void setDec_preeze_amount(Double dec_preeze_amount) {
		this.dec_preeze_amount = dec_preeze_amount;
	}

	public Date getDt_last_time() {
		return dt_last_time;
	}

	public void setDt_last_time(Date dt_last_time) {
		this.dt_last_time = dt_last_time;
	}

	public Long getInt_user_score() {
		return int_user_score;
	}

	public void setInt_user_score(Long int_user_score) {
		this.int_user_score = int_user_score;
	}

	public Double getDec_paypal_amount() {
		return dec_paypal_amount;
	}

	public void setDec_paypal_amount(Double dec_paypal_amount) {
		this.dec_paypal_amount = dec_paypal_amount;
	}

	public Double getDec_nopaypal_amount() {
		return dec_nopaypal_amount;
	}

	public void setDec_nopaypal_amount(Double dec_nopaypal_amount) {
		this.dec_nopaypal_amount = dec_nopaypal_amount;
	}

	public Date getDt_reg_date() {
		return dt_reg_date;
	}

	public void setDt_reg_date(Date dt_reg_date) {
		this.dt_reg_date = dt_reg_date;
	}

	public String getVc_last_ip() {
		return vc_last_ip;
	}

	public void setVc_last_ip(String vc_last_ip) {
		this.vc_last_ip = vc_last_ip;
	}

	public String getVc_pay_password() {
		return vc_pay_password;
	}

	public void setVc_pay_password(String vc_pay_password) {
		this.vc_pay_password = vc_pay_password;
	}

	public Double getDec_extra_account() {
		return dec_extra_account;
	}

	public void setDec_extra_account(Double dec_extra_account) {
		this.dec_extra_account = dec_extra_account;
	}

	public Double getDec_lottery_bean() {
		return dec_lottery_bean;
	}

	public void setDec_lottery_bean(Double dec_lottery_bean) {
		this.dec_lottery_bean = dec_lottery_bean;
	}

	public String getVc_open_id() {
		return vc_open_id;
	}

	public void setVc_open_id(String vc_open_id) {
		this.vc_open_id = vc_open_id;
	}

	public String getVc_from() {
		return vc_from;
	}

	public void setVc_from(String vc_from) {
		this.vc_from = vc_from;
	}
	
	
	

}