package com.easylotto.core.entity.user;

// Generated by MyEclipse - Hibernate Tools

import java.util.Date;

import javax.persistence.Table;

/**
 * EcpEcard generated by MyEclipse - Hibernate Tools
 */
@Table(name = "ecp_user")
public class EcpUser extends AbstractEcpUser implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public EcpUser() {
	}

	/** minimal constructor */
	public EcpUser(Long intAccountId,String vcAccount, String vcPassword, Long intAccType,
			Long intAccStatus, Double decPaypalAmount, Date dtRegTime) {
		super(intAccountId,vcAccount, vcPassword, intAccType, intAccStatus, decPaypalAmount,
				dtRegTime);
	}

	/** full constructor */
	public EcpUser(Long intAccountId, String vcAccount, String vcPassword, Long intAccType,
			Long intAccStatus, Long intGenType, Double decPresentAmount,
			Double decPreezeAmount, Date dtLastTime, Long intUserScore,
			Double decPaypalAmount, Double decNopaypalAmount, Date dtRegTime,
			String vcLastIp, String vcPayPassword,Double decExtraAccount,Double decLotteryBean,String vcOpenId) {
		super(intAccountId,vcAccount, vcPassword, intAccType, intAccStatus, intGenType,
				decPresentAmount, decPreezeAmount, dtLastTime, intUserScore,
				decPaypalAmount, decNopaypalAmount, dtRegTime, vcLastIp,
				vcPayPassword, decExtraAccount, decLotteryBean, vcOpenId);
	}

}
